name: Deploy To Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "19.x" # package.json の engines に合わせた

      - name: Install dependencies
        run: npm install

      # https://github.com/kanadgupta/glitch-sync
      - name: Deploy To Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: "${{ secrets.PROJECT_ID }}"
          auth-token: "${{ secrets.AUTH_TOKEN }}"
